### ISSUE TITLE
Scenario for VoLET or RTP packet streaming in Simulte is neede

### ISSUE THREAD

**Issue by Farhadesfandiar** [inet-framework/simulte#30]
Hi everyone,

I'm new in Omnet++ and in my research, I need to simulate VoLTE packet streaming between 2 UE to evaluate Inter-Packet Delay(IPD) and packet loss of the communication.

I would be grateful if you can introduce me some related scenario about VoLTE or RTP packet stream simulation in Simulte and INET or any link that can be useful in this area? 

Thanks

**Comment by levy** [comment]
This is not the right forum to ask such questions, use the mailing list instead.

**Comment by Farhadesfandiar** [comment]
Hello Dear  Levente,

I am new in SimuLTE, and with the website. I am doing my research on VoLTE
packets (Covert Timing Channel) as my master thesis.
I didn't find any mailing list there. If it's possible would you guide me
through how to find some scenarios or resources?
I would be really thankful for your help.
Thank you in advance.

Best regards,

Ali Esfandiar
+905338370264
